/* =================================================================
   UVSQ Calendar Fetcher – app.js  (Client-side tool)
   ================================================================
   Hard-coded M1 Info S2 modules · Client-side .ics generation
   No Flask / no server required. Reads pre-fetched celcat-data.json.
   ================================================================= */

// -----------------------------------------------------------------
// Hard-coded M1 Informatique S2 modules (2024-2025)
// -----------------------------------------------------------------
const M1_S2_MODULES = [
  { code: "MIN17201", name: "Programmation, GL et Preuve" },
  { code: "MIN17211", name: "Méthodes de Ranking" },
  { code: "MIN17212", name: "Simulation" },
  { code: "MIN17213", name: "Tuning de BD" },
  { code: "MIN17214", name: "Conception de BD" },
  { code: "MIN17215", name: "Protocoles IP" },
  { code: "MIN17216", name: "Réseaux étendus" },
  { code: "MIN17217", name: "Application Web et Sécurité" },
  { code: "MIN17218", name: "Calcul Sécurisé" },
  { code: "MSANGS2I", name: "Anglais S2 M1 Infos" },
];
const MAX_GROUPS = 4;

// -----------------------------------------------------------------
// i18n
// -----------------------------------------------------------------
const I18N = {
  fr: {
    heroBadge: "Outil Calendrier Universitaire",
    heroLine1: "Construis ton",
    heroLine2: "emploi du temps",
    heroSub: "Sélectionne tes modules M1 Info S2, choisis ton groupe TD et télécharge ton calendrier .ics.",
    loadingData: "Chargement des données...",
    errorLoad: "Données indisponibles.",
    errorNoData: "Les données CELCAT ne sont pas encore disponibles. Le fichier sera généré automatiquement par le workflow GitHub Actions.",
    retry: "Réessayer",
    semester: "Semestre S2 — 2024/2025",
    dateFrom: "Du",
    dateTo: "Au",
    pickerTitle: "Sélectionne tes modules",
    pickerSub: "Coche ceux de ton contrat d'études et indique ton groupe de TD.",
    selectAll: "Tout sélectionner",
    deselectAll: "Tout décocher",
    examNote: "Examens, partiels et soutenances sont toujours inclus automatiquement.",
    generate: "Générer et télécharger .ics",
    generating: "Génération en cours...",
    noModules: "Aucun module trouvé.",
    selectAtLeast: "Sélectionne au moins un module.",
    selectGroup: "Choisis un groupe TD pour : ",
    eventsFound: "événements trouvés",
    docs: "Documentation",
    configDownload: "Télécharger le config JSON",
    configTitle: "Configuration pour auto-actualisation",
    configDesc: "Télécharge ce fichier calendar-config.json et utilise-le avec GitHub Actions pour un calendrier auto-actualisé.",
    configSteps: [
      "Fork le dépôt GitHub du projet.",
      "Remplace le fichier calendar-config.json par celui téléchargé.",
      "Active GitHub Actions dans ton fork (onglet Actions).",
      "Active GitHub Pages (Settings → Pages → Source: main).",
      "Ton calendrier sera mis à jour automatiquement toutes les 6 heures.",
    ],
    configHowTo: "Comment mettre en place l'auto-actualisation",
    orUpdate: "ou mettre à jour un fichier existant",
    updateTitle: "Mettre à jour ton calendrier",
    updateDesc: "Envoie un fichier .ics généré précédemment. On détectera tes modules et téléchargera une version actualisée.",
    updateDropText: "Glisse ton fichier .ics ici ou clique pour parcourir",
    updateDropHint: "Uniquement les fichiers .ics générés par cet outil",
    updateUploading: "Analyse et mise à jour en cours...",
    updateSuccess: "Calendrier mis à jour ! Téléchargement lancé.",
    updateError: "Erreur lors de la mise à jour.",
    updateNoData: "Impossible : données CELCAT non chargées.",
  },
  en: {
    heroBadge: "University Calendar Tool",
    heroLine1: "Build your",
    heroLine2: "perfect schedule",
    heroSub: "Select your M1 Info S2 modules, pick your TD group, and download your .ics calendar.",
    loadingData: "Loading calendar data...",
    errorLoad: "Data unavailable.",
    errorNoData: "CELCAT data is not yet available. The file will be auto-generated by the GitHub Actions workflow.",
    retry: "Retry",
    semester: "Semester S2 — 2024/2025",
    dateFrom: "From",
    dateTo: "To",
    pickerTitle: "Select your modules",
    pickerSub: "Check the ones from your study contract and set your TD group number.",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    examNote: "Exams, midterms and defenses are always included automatically.",
    generate: "Generate & download .ics",
    generating: "Generating...",
    noModules: "No modules found.",
    selectAtLeast: "Select at least one module.",
    selectGroup: "Select a TD group for: ",
    eventsFound: "events detected",
    docs: "Documentation",
    configDownload: "Download config JSON",
    configTitle: "Configuration for auto-updates",
    configDesc: "Download this calendar-config.json and use it with GitHub Actions for an auto-updating calendar.",
    configSteps: [
      "Fork the project's GitHub repository.",
      "Replace the calendar-config.json file with the one you downloaded.",
      "Enable GitHub Actions in your fork (Actions tab).",
      "Enable GitHub Pages (Settings → Pages → Source: main).",
      "Your calendar will auto-update every 6 hours.",
    ],
    configHowTo: "How to set up auto-updates",
    orUpdate: "or update an existing file",
    updateTitle: "Update your calendar",
    updateDesc: "Upload a previously generated .ics file. We'll detect your modules and download a refreshed version.",
    updateDropText: "Drop your .ics file here or click to browse",
    updateDropHint: "Only .ics files generated by this tool",
    updateUploading: "Analyzing and updating...",
    updateSuccess: "Calendar updated! Download started.",
    updateError: "Error updating the file.",
    updateNoData: "Cannot update: CELCAT data not loaded.",
  },
};

// -----------------------------------------------------------------
// State
// -----------------------------------------------------------------
let lang = localStorage.getItem("lang") || (navigator.language.startsWith("fr") ? "fr" : "en");
let celcatData = null;
let totalEvents = 0;

const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);

// -----------------------------------------------------------------
// Theme
// -----------------------------------------------------------------
function getSystemTheme() {
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}
function applyTheme(choice) {
  localStorage.setItem("theme", choice);
  const eff = choice === "auto" ? getSystemTheme() : choice;
  document.documentElement.setAttribute("data-theme", eff);
}
function initTheme() {
  applyTheme(localStorage.getItem("theme") || "auto");
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", () => {
    if ((localStorage.getItem("theme") || "auto") === "auto") applyTheme("auto");
  });
}

// -----------------------------------------------------------------
// i18n
// -----------------------------------------------------------------
function t(key) { return (I18N[lang] || I18N.en)[key] || key; }

function setLang(l) {
  lang = l;
  localStorage.setItem("lang", l);
  $$(".lang-btn").forEach((b) => b.classList.toggle("active", b.dataset.lang === l));
  renderUI();
}

function renderUI() {
  $$("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (I18N[lang] && I18N[lang][key] && typeof I18N[lang][key] === "string") {
      el.textContent = I18N[lang][key];
    }
  });
  $$(".lang-btn").forEach((b) => b.classList.toggle("active", b.dataset.lang === lang));
  if (totalEvents) {
    const ct = $("#eventCountText");
    if (ct) ct.textContent = `${totalEvents} ${t("eventsFound")}`;
  }
  const btn = $("#btnGenerate");
  if (btn && !btn.disabled) {
    const sp = btn.querySelector(".btn-generate-text");
    if (sp) sp.textContent = t("generate");
  }
  renderModules();
}

// -----------------------------------------------------------------
// GSAP entrance animation
// -----------------------------------------------------------------
function playEntrance() {
  if (typeof gsap === "undefined") return;
  gsap.registerPlugin(ScrollTrigger);

  const tl = gsap.timeline({ defaults: { ease: "power3.out" } });

  tl.to(".navbar", { y: 0, duration: .6, ease: "power2.out" }, 0);
  tl.fromTo(".blob-1", { x: -120, y: -80, scale: .6 }, { x: 0, y: 0, scale: 1, duration: 1.8, ease: "power1.out" }, 0);
  tl.fromTo(".blob-2", { x: 100, y: 60, scale: .5 }, { x: 0, y: 0, scale: 1, duration: 2, ease: "power1.out" }, 0.1);
  tl.fromTo(".blob-3", { x: -60, y: 100, scale: .5 }, { x: 0, y: 0, scale: 1, duration: 2.2, ease: "power1.out" }, 0.2);
  tl.fromTo(".hero-badge", { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: .5 }, .3);
  tl.fromTo(".title-line", { opacity: 0, y: 40 }, { opacity: 1, y: 0, stagger: .12, duration: .6 }, .45);
  tl.fromTo(".hero-sub", { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: .5 }, .75);
  tl.fromTo(".hero-loader", { opacity: 0 }, { opacity: 1, duration: .4 }, .9);

  gsap.to(".blob-1", { x: 30, y: -20, duration: 8, repeat: -1, yoyo: true, ease: "sine.inOut" });
  gsap.to(".blob-2", { x: -25, y: 15, duration: 10, repeat: -1, yoyo: true, ease: "sine.inOut" });
  gsap.to(".blob-3", { x: 20, y: -25, duration: 9, repeat: -1, yoyo: true, ease: "sine.inOut" });
}

// -----------------------------------------------------------------
// Transition: hero → main content
// -----------------------------------------------------------------
function transitionToContent() {
  const mc = $("#mainContent");

  if (typeof gsap === "undefined") {
    const hero = $("#heroSection");
    hero.style.minHeight = "auto";
    hero.style.paddingTop = "6rem";
    hero.style.paddingBottom = "2rem";
    $(".hero-loader").style.display = "none";
    const sc = $("#scrollHint");
    if (sc) sc.style.display = "none";
    mc.style.opacity = "1";
    mc.style.visibility = "visible";
    return;
  }

  const tl = gsap.timeline({
    defaults: { ease: "power3.inOut" },
    onComplete: () => {
      mc.style.opacity = "1";
      mc.style.visibility = "visible";
      gsap.set(".module-card", { clearProps: "opacity,y" });
    }
  });

  tl.to(".hero-loader", { opacity: 0, duration: .3 }, 0);
  tl.to("#heroSection", {
    minHeight: "auto", paddingTop: "6.5rem", paddingBottom: "1.5rem",
    duration: .7, ease: "power2.inOut"
  }, .2);
  tl.to("#scrollHint", { opacity: 0, duration: .2 }, 0);
  tl.fromTo(mc, { opacity: 0, visibility: "hidden" }, { opacity: 1, visibility: "visible", duration: .5 }, .5);
  tl.fromTo("#infoBar", { y: 30, opacity: 0 }, { y: 0, opacity: 1, duration: .5 }, .6);
  tl.fromTo(".picker-header", { y: 20, opacity: 0 }, { y: 0, opacity: 1, duration: .4 }, .7);
  tl.fromTo(".module-card", { y: 20, opacity: 0 }, { y: 0, opacity: 1, stagger: .04, duration: .35 }, .8);
  tl.fromTo(".exam-notice", { y: 15, opacity: 0 }, { y: 0, opacity: 1, duration: .3 }, 1);
  tl.fromTo(".btn-generate", { y: 15, opacity: 0 }, { y: 0, opacity: 1, duration: .3 }, 1.05);
  tl.set("#scrollHint", { display: "none" }, .5);
}

// -----------------------------------------------------------------
// Load pre-fetched CELCAT data
// -----------------------------------------------------------------
async function loadData() {
  const status = $("#loadStatus");
  status.textContent = t("loadingData");
  status.style.color = "";
  $("#retryBtn").classList.add("hidden");

  try {
    const resp = await fetch("celcat-data.json");
    if (!resp.ok) throw new Error(t("errorNoData"));
    celcatData = await resp.json();
    totalEvents = celcatData.length;
    const ct = $("#eventCountText");
    if (ct) ct.textContent = `${totalEvents} ${t("eventsFound")}`;
  } catch (_) {
    // Data not available yet — modules still display (hard-coded)
  }

  renderModules();
  transitionToContent();
  setTimeout(() => {
    const mc = document.getElementById("mainContent");
    if (mc) { mc.style.opacity = "1"; mc.style.visibility = "visible"; }
  }, 2200);
}

// -----------------------------------------------------------------
// Render module cards (hard-coded list)
// -----------------------------------------------------------------
function renderModules() {
  const grid = $("#moduleGrid");
  if (!grid) return;

  // Preserve current selections
  const prev = {};
  $$(".module-cb").forEach((cb) => {
    if (cb.checked) {
      const sel = $(`.grp-select[data-code="${cb.dataset.code}"]`);
      prev[cb.dataset.code] = sel ? sel.value : "";
    }
  });

  grid.innerHTML = "";

  M1_S2_MODULES.forEach((mod) => {
    const card = document.createElement("div");
    card.className = "module-card";
    card.dataset.code = mod.code;

    const cb = document.createElement("input");
    cb.type = "checkbox";
    cb.className = "module-cb";
    cb.dataset.code = mod.code;

    const info = document.createElement("div");
    info.className = "module-info";

    const codeDiv = document.createElement("div");
    codeDiv.className = "module-code";
    codeDiv.textContent = mod.code;
    const nameDiv = document.createElement("div");
    nameDiv.className = "module-name";
    nameDiv.textContent = mod.name;
    nameDiv.title = mod.name;
    info.appendChild(codeDiv);
    info.appendChild(nameDiv);

    const sel = document.createElement("select");
    sel.className = "grp-select";
    sel.dataset.code = mod.code;
    sel.disabled = true;
    sel.innerHTML = '<option value="">—</option>';
    for (let i = 1; i <= MAX_GROUPS; i++)
      sel.innerHTML += `<option value="${i}">${i}</option>`;

    card.addEventListener("click", (e) => {
      if (e.target === sel || e.target === cb) return;
      cb.checked = !cb.checked;
      cb.dispatchEvent(new Event("change"));
    });

    cb.addEventListener("change", () => {
      sel.disabled = !cb.checked;
      card.classList.toggle("selected", cb.checked);
    });

    sel.addEventListener("click", (e) => e.stopPropagation());

    card.appendChild(cb);
    card.appendChild(info);
    card.appendChild(sel);
    grid.appendChild(card);

    // Restore previous selection
    if (prev[mod.code]) {
      cb.checked = true;
      cb.dispatchEvent(new Event("change"));
      sel.value = prev[mod.code];
    }
  });
}

// -----------------------------------------------------------------
// Select / Deselect all
// -----------------------------------------------------------------
function toggleAll(state) {
  $$(".module-cb").forEach((cb) => {
    cb.checked = state;
    cb.dispatchEvent(new Event("change"));
  });
}

// =================================================================
//  EVENT FILTERING  (ported from Python event_filter.py)
// =================================================================
const MODULE_CODE_RE = /(MIN\d{5}|MSANGS\w+)/gi;
const GROUP_RE = /M1\s+Info\s+gr\.\s*(\d+)/gi;
const ROOM_RE = /<br\s*\/?>\s*([A-Z0-9][A-Za-z0-9 ]*\s+-\s+[A-Z][A-Za-z0-9 /().,'\u2013&;#\-]+\[.+?\])/;
const EXAM_KEYWORDS = [
  "examen", "partiel", "contrôle", "controle",
  "épreuve", "epreuve", "ct ", "ct\n",
  "ds ", "ds\n", "soutenance", "rattrapage",
  "exam", "evaluation", "évaluation",
  "jury", "résultat", "resultat",
];
const COLORS = {
  CM: "#27AE60", TD: "#E91E63", TP: "#2196F3",
  EXAM: "#FF5722", DEFAULT: "#9E9E9E",
};

function cleanHtml(raw) {
  let text = raw.replace(/<br\s*\/?>/gi, "\n").replace(/<[^>]+>/g, "");
  const el = document.createElement("textarea");
  el.innerHTML = text;
  return el.value.trim();
}

function extractModuleCodes(text) {
  const codes = new Set();
  let m;
  MODULE_CODE_RE.lastIndex = 0;
  while ((m = MODULE_CODE_RE.exec(text)) !== null) codes.add(m[1].toUpperCase());
  return [...codes];
}

function extractGroupNumbers(text) {
  const nums = [];
  let m;
  GROUP_RE.lastIndex = 0;
  while ((m = GROUP_RE.exec(text)) !== null) nums.push(parseInt(m[1]));
  return nums;
}

function extractLocation(descRaw) {
  const m = ROOM_RE.exec(descRaw);
  if (m) {
    const loc = cleanHtml(m[1]);
    MODULE_CODE_RE.lastIndex = 0;
    if (MODULE_CODE_RE.test(loc)) return "";
    return loc;
  }
  return "";
}

function isExamEvent(raw) {
  const text = ((raw.title || "") + " " + (raw.description || "") + " " + (raw.eventCategory || "")).toLowerCase();
  return EXAM_KEYWORDS.some((kw) => text.includes(kw));
}

function eventCategory(raw) {
  const cat = (raw.eventCategory || "").trim();
  if (cat) return cat;
  const desc = (raw.description || "") + " " + (raw.title || "");
  for (const token of ["CM", "TD Cartable Numérique", "TD", "TP"]) {
    if (desc.includes(token)) return token.split(" ")[0];
  }
  return "OTHER";
}

function buildUid(raw) {
  if (raw.id) return raw.id + "@celcat.uvsq.fr";
  const str = (raw.start || "") + (raw.description || "");
  let h = 0;
  for (let i = 0; i < str.length; i++) h = ((h << 5) - h + str.charCodeAt(i)) | 0;
  return Math.abs(h).toString(16) + "@celcat.uvsq.fr";
}

/**
 * Filter raw CELCAT events by selected modules.
 * @param {Array} rawEvents - Raw event objects from celcat-data.json
 * @param {Object} modules - { "MIN17201": { name, td_group }, ... }
 */
function filterEvents(rawEvents, modules, includeExams) {
  if (includeExams === undefined) includeExams = true;
  const enrolledCodes = new Set(Object.keys(modules).map((c) => c.toUpperCase()));
  const kept = [];
  const seen = new Set();

  for (const raw of rawEvents) {
    const descRaw = raw.description || "";
    const titleRaw = raw.title || "";
    const allText = titleRaw + " " + descRaw;

    const isExam = includeExams && isExamEvent(raw);
    const codes = extractModuleCodes(allText);
    const matchingCodes = codes.filter((c) => enrolledCodes.has(c));

    if (!matchingCodes.length && !isExam) continue;

    const category = eventCategory(raw);

    // Group filtering for TD/TP (exams always pass)
    if (!isExam && (category.startsWith("TD") || category.startsWith("TP"))) {
      const groupNums = extractGroupNumbers(allText);
      if (groupNums.length) {
        let match = false;
        for (const code of matchingCodes) {
          const expected = modules[code] && modules[code].td_group;
          if (expected != null && groupNums.includes(expected)) { match = true; break; }
        }
        if (!match) continue;
      }
    }

    const descClean = cleanHtml(descRaw);
    let locationClean = extractLocation(descRaw);
    if (!locationClean) locationClean = cleanHtml(raw.location || "");

    let summary;
    if (matchingCodes.length) {
      const primaryCode = matchingCodes[0];
      const modName = (modules[primaryCode] && modules[primaryCode].name) || primaryCode;
      summary = `${category} - ${modName} - ${primaryCode}`;
    } else if (isExam) {
      summary = titleRaw ? cleanHtml(titleRaw) : `${category} - Exam`;
    } else {
      continue;
    }

    const color = raw.backgroundColor || (isExam ? COLORS.EXAM : (COLORS[category] || COLORS.DEFAULT));
    const uid = buildUid(raw);

    const descLines = [category];
    if (locationClean) descLines.push(locationClean);
    for (const code of (matchingCodes.length ? matchingCodes : codes)) {
      const mname = (modules[code] && modules[code].name) || code;
      descLines.push(`${code}-${mname} [${code}]`);
    }

    const dedup = `${raw.start || ""}|${raw.end || ""}|${summary}`;
    if (seen.has(dedup)) continue;
    seen.add(dedup);

    kept.push({
      uid, dtstart: raw.start || "", dtend: raw.end || "",
      summary, description: descLines.join("\\n"),
      location: locationClean, color, category,
    });
  }
  return kept;
}

// =================================================================
//  ICS GENERATION  (ported from Python ics_generator.py)
// =================================================================
function toIcsDt(iso) {
  return iso.replace(/[-:]/g, "").replace(/[^0-9T]/g, "").slice(0, 15);
}

function esc(text) {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\r\n/g, "\\n")
    .replace(/\n/g, "\\n");
}

function foldLine(line) {
  if (line.length <= 75) return line;
  const parts = [];
  let remaining = line;
  let first = true;
  while (remaining.length > (first ? 75 : 74)) {
    const cut = first ? 75 : 74;
    parts.push(remaining.slice(0, cut));
    remaining = remaining.slice(cut);
    first = false;
  }
  if (remaining) parts.push(remaining);
  return parts.join("\r\n ");
}

function generateIcs(events, calName) {
  if (!calName) calName = "CELCAT - UVSQ Calendar";
  const now = new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z/, "").slice(0, 15) + "Z";
  const lines = [
    "BEGIN:VCALENDAR", "VERSION:2.0",
    "PRODID:-//CELCAT to ICS//UVSQ Calendar//EN",
    "CALSCALE:GREGORIAN", "METHOD:PUBLISH",
    "X-WR-CALNAME:" + calName,
    "X-WR-TIMEZONE:Europe/Paris",
    "X-WR-CALDESC:University calendar from CELCAT",
  ];
  for (const ev of events) {
    const sEsc = esc(ev.summary);
    const dEsc = esc(ev.description);
    const lEsc = ev.location ? esc(ev.location) : "";
    lines.push("BEGIN:VEVENT");
    lines.push("UID:" + ev.uid);
    lines.push("DTSTAMP:" + now);
    lines.push("DTSTART:" + toIcsDt(ev.dtstart));
    lines.push("DTEND:" + toIcsDt(ev.dtend));
    lines.push(foldLine("SUMMARY:" + sEsc));
    lines.push(foldLine("DESCRIPTION:" + dEsc));
    if (lEsc) lines.push(foldLine("LOCATION:" + lEsc));
    lines.push("COLOR:" + ev.color);
    lines.push("CATEGORIES:" + ev.category);
    lines.push("STATUS:CONFIRMED");
    lines.push("BEGIN:VALARM");
    lines.push("TRIGGER:-PT30M");
    lines.push("ACTION:DISPLAY");
    lines.push(foldLine("DESCRIPTION:Reminder: " + sEsc));
    lines.push("END:VALARM");
    lines.push("BEGIN:VALARM");
    lines.push("TRIGGER:-P1D");
    lines.push("ACTION:DISPLAY");
    lines.push(foldLine("DESCRIPTION:Reminder: " + sEsc + " (Tomorrow)"));
    lines.push("END:VALARM");
    lines.push("END:VEVENT");
  }
  lines.push("END:VCALENDAR");
  return lines.join("\r\n") + "\r\n";
}

// -----------------------------------------------------------------
// Collect selected modules from the picker
// -----------------------------------------------------------------
function collectSelected() {
  const errEl = $("#formError");
  errEl.textContent = "";
  const selected = {};
  let hasError = false;

  $$(".module-cb:checked").forEach((cb) => {
    const code = cb.dataset.code;
    const sel = $(`.grp-select[data-code="${code}"]`);
    const grp = sel ? sel.value : "";
    if (!grp) {
      const mod = M1_S2_MODULES.find((m) => m.code === code);
      errEl.textContent = t("selectGroup") + (mod ? mod.name : code);
      hasError = true;
      return;
    }
    const mod = M1_S2_MODULES.find((m) => m.code === code);
    selected[code] = {
      name: mod ? mod.name : code,
      td_group: parseInt(grp),
      td_group_label: "M1 Info gr. " + grp,
    };
  });

  if (hasError) return null;
  if (!Object.keys(selected).length) {
    errEl.textContent = t("selectAtLeast");
    return null;
  }
  return selected;
}

// -----------------------------------------------------------------
// Generate & download .ics
// -----------------------------------------------------------------
function generate() {
  const btn = $("#btnGenerate");
  const errEl = $("#formError");
  errEl.textContent = "";

  if (!celcatData) {
    errEl.textContent = t("errorNoData");
    return;
  }

  const modules = collectSelected();
  if (!modules) return;

  btn.disabled = true;
  const sp = btn.querySelector(".btn-generate-text");
  if (sp) sp.textContent = t("generating");

  try {
    const filtered = filterEvents(celcatData, modules, true);
    if (!filtered.length) {
      errEl.textContent = lang === "fr"
        ? "Aucun événement trouvé pour cette sélection."
        : "No events found for this selection.";
      return;
    }
    const ics = generateIcs(filtered);
    downloadBlob(ics, "my_calendar.ics", "text/calendar;charset=utf-8");
  } catch (e) {
    errEl.textContent = e.message;
  } finally {
    btn.disabled = false;
    if (sp) sp.textContent = t("generate");
  }
}

// -----------------------------------------------------------------
// Subscribe → Download config JSON + show fork instructions
// -----------------------------------------------------------------
function subscribe() {
  const errEl = $("#formError");
  errEl.textContent = "";

  const modules = collectSelected();
  if (!modules) return;

  const config = {
    modules: modules,
    start_date: $("#startDate").value,
    end_date: $("#endDate").value,
    include_exams: true,
  };

  downloadBlob(JSON.stringify(config, null, 2), "calendar-config.json", "application/json;charset=utf-8");

  // Show fork instructions in the result card
  const result = $("#subResult");
  result.classList.remove("hidden");

  const header = result.querySelector("h3");
  if (header) header.textContent = t("configTitle");
  const desc = result.querySelector(".sub-desc");
  if (desc) desc.textContent = t("configDesc");

  // Hide URL row + webcal (not applicable for client-side)
  const urlRow = result.querySelector(".sub-url-row");
  if (urlRow) urlRow.style.display = "none";
  const webcal = result.querySelector(".btn-webcal");
  if (webcal) webcal.style.display = "none";

  const stepsEl = $("#subSteps");
  stepsEl.innerHTML = "";
  const steps = t("configSteps");
  if (Array.isArray(steps)) {
    steps.forEach((s) => {
      const li = document.createElement("li");
      li.textContent = s;
      stepsEl.appendChild(li);
    });
  }
  const howto = result.querySelector("summary");
  if (howto) howto.textContent = t("configHowTo");

  result.scrollIntoView({ behavior: "smooth", block: "center" });
}

// -----------------------------------------------------------------
// Upload & Update existing .ics  (client-side)
// -----------------------------------------------------------------
function uploadUpdate(file) {
  const statusEl = $("#updateStatus");
  statusEl.classList.remove("hidden");
  statusEl.className = "update-status";
  statusEl.textContent = t("updateUploading");

  if (!celcatData) {
    statusEl.textContent = t("updateNoData");
    statusEl.classList.add("update-error");
    return;
  }

  const reader = new FileReader();
  reader.onload = function (e) {
    try {
      const icsText = e.target.result;
      const modules = parseIcsModules(icsText);
      if (!Object.keys(modules).length) {
        throw new Error(lang === "fr"
          ? "Aucun module détecté dans le fichier."
          : "No modules detected in the file.");
      }
      const filtered = filterEvents(celcatData, modules, true);
      if (!filtered.length) {
        throw new Error(lang === "fr" ? "Aucun événement trouvé." : "No events found.");
      }
      const ics = generateIcs(filtered);
      downloadBlob(ics, "my_calendar_updated.ics", "text/calendar;charset=utf-8");
      statusEl.textContent = t("updateSuccess");
      statusEl.classList.add("update-success");
    } catch (err) {
      statusEl.textContent = t("updateError") + " " + err.message;
      statusEl.classList.add("update-error");
    }
  };
  reader.readAsText(file);
}

function parseIcsModules(icsText) {
  const modules = {};
  const lines = icsText.split(/\r?\n/);
  let currentCodes = [];

  for (const line of lines) {
    MODULE_CODE_RE.lastIndex = 0;
    let m;
    while ((m = MODULE_CODE_RE.exec(line)) !== null) {
      const code = m[1].toUpperCase();
      if (!modules[code]) {
        const mod = M1_S2_MODULES.find((x) => x.code === code);
        modules[code] = { name: mod ? mod.name : code, td_group: 1, td_group_label: "M1 Info gr. 1" };
      }
      currentCodes.push(code);
    }

    GROUP_RE.lastIndex = 0;
    const gm = GROUP_RE.exec(line);
    if (gm) {
      const grp = parseInt(gm[1]);
      for (const code of currentCodes) {
        if (modules[code]) {
          modules[code].td_group = grp;
          modules[code].td_group_label = "M1 Info gr. " + grp;
        }
      }
    }

    if (line.startsWith("END:VEVENT")) {
      currentCodes = [];
    }
  }
  return modules;
}

// -----------------------------------------------------------------
// Drag & drop for update
// -----------------------------------------------------------------
function initUpdateDrop() {
  const drop = $("#updateDrop");
  const input = $("#updateFile");
  if (!drop || !input) return;

  input.addEventListener("change", () => {
    if (input.files.length) uploadUpdate(input.files[0]);
  });

  drop.addEventListener("dragover", (e) => {
    e.preventDefault();
    drop.classList.add("dragover");
  });
  drop.addEventListener("dragleave", () => drop.classList.remove("dragover"));
  drop.addEventListener("drop", (e) => {
    e.preventDefault();
    drop.classList.remove("dragover");
    const f = e.dataTransfer.files[0];
    if (f && f.name.toLowerCase().endsWith(".ics")) uploadUpdate(f);
  });
}

// -----------------------------------------------------------------
// Download helper
// -----------------------------------------------------------------
function downloadBlob(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// -----------------------------------------------------------------
// Copy helper
// -----------------------------------------------------------------
function copySubUrl() {
  const input = $("#subUrl");
  if (!input || !input.value) return;
  navigator.clipboard.writeText(input.value).then(() => {
    const btn = $("#btnCopy");
    const span = btn && btn.querySelector("span");
    if (span) {
      const prev = span.textContent;
      span.textContent = lang === "fr" ? "Copié !" : "Copied!";
      setTimeout(() => { span.textContent = prev; }, 2000);
    }
  });
}

// -----------------------------------------------------------------
// Init
// -----------------------------------------------------------------
document.addEventListener("DOMContentLoaded", () => {
  if (!document.getElementById("loadStatus")) return;
  initTheme();
  setLang(lang);
  playEntrance();
  loadData();
  initUpdateDrop();
});
